Repository CS3247-Game-Development-Team-6/Doodles, pull requests merged in 2022-11, with the labels that each got.

#402 Fix gel tower shooting when HP is 0
  Assets/Scripts/Towers/GelExplosionTower.cs
Labels: bug

#379 Balance levels, chunks, waves
  Assets/ScriptableObjects/Elements/StatusEffects/FrozenEffect.asset
  Assets/ScriptableObjects/Elements/StatusEffects/SlowEffect.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_1.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_2.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_3.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_4.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_5.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_6.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_7.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelWater.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelWater.asset
  Assets/ScriptableObjects/Towers/Mortar/0_MortarBase.asset
  Assets/ScriptableObjects/Towers/Mortar/0_MortarFire.asset
  Assets/ScriptableObjects/Towers/Mortar/0_MortarIce.asset
  Assets/ScriptableObjects/Towers/Mortar/0_MortarWater.asset
  Assets/ScriptableObjects/Towers/Mortar/1_MortarBase.asset
  Assets/ScriptableObjects/Towers/Mortar/1_MortarFire.asset
  Assets/ScriptableObjects/Towers/Mortar/1_MortarIce.asset
  Assets/ScriptableObjects/Towers/Mortar/1_MortarWater.asset
  Assets/Scripts/Enemy/EnemyActiveEffectsSystem/GelExplosionEffect.cs
Labels: enhancement, High Priority

#409 Update balancing / fix notes
  Assets/3rd-Party/Font/Bowlby/BowlbyOneSC-RedTitle.asset
  Assets/Prefabs/UI/HUD/MainUI.prefab
  Assets/Prefabs/UI/HUD/NoteCard.prefab
  Assets/Scenes/Levels/TutorialScene-beta.unity
  Assets/ScriptableObjects/Elements/StatusEffects/SlowEffect.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_1.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_2.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_3.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_4.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_5.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_6.asset
  Assets/ScriptableObjects/Levels/0_Tutorial_Chunk_7.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_1.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_2.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_3.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_4.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_5.asset
  Assets/ScriptableObjects/Levels/1_Spider_Chunk_6.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_1.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_2.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_3.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_4.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_5.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_6.asset
  Assets/ScriptableObjects/Levels/2_Ghost_Chunk_7.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_1.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_2.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_3.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_4.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_5.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_6.asset
  Assets/ScriptableObjects/Levels/3_Clown_Chunk_7.asset
  UserSettings/EditorUserSettings.asset
Labels: enhancement
