Repository CS3247-Game-Development-Team-6/Doodles, pull requests merged in 2022-10, with the labels that each got.

#245 Debug node UI display bugs
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaBase.asset
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaFire.asset
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaIce.asset
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaWater.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaBase.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaFire.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaIce.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaWater.asset
  Assets/ScriptableObjects/Towers/Cannon/0_CannonBase.asset
  Assets/ScriptableObjects/Towers/Cannon/0_CannonFire.asset
  Assets/ScriptableObjects/Towers/Cannon/0_CannonIce.asset
  Assets/ScriptableObjects/Towers/Cannon/0_CannonWater.asset
  Assets/ScriptableObjects/Towers/Cannon/1_CannonBase.asset
  Assets/ScriptableObjects/Towers/Cannon/1_CannonFire.asset
  Assets/ScriptableObjects/Towers/Cannon/1_CannonIce.asset
  Assets/ScriptableObjects/Towers/Cannon/1_CannonWater.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelWater.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelWater.asset
  Assets/ScriptableObjects/Towers/Spikey/0_SpikeyBase.asset
  Assets/ScriptableObjects/Towers/Spikey/0_SpikeyFire.asset
  Assets/ScriptableObjects/Towers/Spikey/0_SpikeyIce.asset
  Assets/ScriptableObjects/Towers/Spikey/0_SpikeyWater.asset
  Assets/ScriptableObjects/Towers/Spikey/1_SpikeyBase.asset
  Assets/ScriptableObjects/Towers/Spikey/1_SpikeyFire.asset
  Assets/ScriptableObjects/Towers/Spikey/1_SpikeyIce.asset
  Assets/ScriptableObjects/Towers/Spikey/1_SpikeyWater.asset
  Assets/Scripts/Towers/Tower.cs
  Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
Labels: bug

#246 Debug gel tower upgrade btn
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaIce.asset
  Assets/ScriptableObjects/Towers/Ballista/0_BallistaWater.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaIce.asset
  Assets/ScriptableObjects/Towers/Ballista/1_BallistaWater.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/0_GelWater.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelBase.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelFire.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelIce.asset
  Assets/ScriptableObjects/Towers/Gel Explosion/1_GelWater.asset
  Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
Labels: bug

#284 Move the property of damageFixCost into Tower instance
  Assets/Scripts/GameManager/TowerManager.cs
  Assets/Scripts/Towers/Tower.cs
  Assets/Scripts/Towers/TowerInfo.cs
  Assets/Scripts/UI/NodeUI.cs
  Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
  UserSettings/EditorUserSettings.asset
Labels: bug

#287 Fix player attack bug
  Assets/Prefabs/Enemy/Clowns/Curse Clown.prefab
  Assets/Prefabs/Enemy/Clowns/Normal Clown.prefab
  Assets/Prefabs/Enemy/Clowns/Surprise Clown.prefab
  Assets/Prefabs/Enemy/Graveyards/Demon.prefab
  Assets/Prefabs/Enemy/Graveyards/Ghost.prefab
  Assets/Prefabs/Enemy/Graveyards/Invulnerable Ghost.prefab
  Assets/Prefabs/Enemy/Spiders/FireRangeSpider.prefab
  Assets/Prefabs/Enemy/Spiders/IceRangeSpider.prefab
  Assets/Prefabs/Enemy/Spiders/MeleeSpider.prefab
  Assets/Prefabs/Enemy/Spiders/RangeSpider.prefab
  Assets/Prefabs/Enemy/Spiders/WaterRangeSpider.prefab
  Assets/Prefabs/Enemy/Tutorials/Boss/Enemy_Boss.prefab
  Assets/Prefabs/Enemy/Tutorials/Fast/Enemy_Fast.prefab
  Assets/Prefabs/Enemy/Tutorials/Simple/Enemy_Simple.prefab
  Assets/Prefabs/Enemy/Tutorials/Tough/Enemy_Tough.prefab
  Assets/Prefabs/Map/BasePrefab.prefab
  Assets/Prefabs/Map/HealthCanvas.prefab
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Towers/Misc/HealthCanvas.prefab
  Assets/Prefabs/Towers/Misc/TowerHealthCanvas.prefab
  UserSettings/EditorUserSettings.asset
Labels: High Priority

#305 Player attack fix
  Assets/Prefabs/Map/Ground.meta
  Assets/Prefabs/Map/Ground/GroundClown.prefab
  Assets/Prefabs/Map/Ground/GroundClown.prefab.meta
  Assets/Prefabs/Map/Ground/GroundGhost.prefab
  Assets/Prefabs/Map/Ground/GroundGhost.prefab.meta
  Assets/Prefabs/Map/Ground/GroundSpider.prefab
  Assets/Prefabs/Map/Ground/GroundSpider.prefab.meta
  Assets/Prefabs/Map/Ground/GroundTutorial.prefab
  Assets/Prefabs/Map/Ground/GroundTutorial.prefab.meta
  Assets/Scenes/Levels/ClownScene-beta.unity
  Assets/Scenes/Levels/GhostScene-beta.unity
  Assets/Scenes/Levels/SpiderScene-beta.unity
  Assets/Scenes/Levels/TutorialScene-beta.unity
  UserSettings/EditorUserSettings.asset
Labels: High Priority

#318 Refinement for player attacks; Fix for player movement when spell select is up
  Assets/ParticleSystems/SparkEffect.meta
  Assets/ParticleSystems/SparkEffect/PS_Spark.prefab
  Assets/ParticleSystems/SparkEffect/PS_Spark.prefab.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Player/Sounds.meta
  Assets/Prefabs/Player/Sounds/SoundFireBullet.prefab
  Assets/Prefabs/Player/Sounds/SoundFireBullet.prefab.meta
  Assets/Prefabs/Player/Sounds/SoundSwordSwing.prefab
  Assets/Prefabs/Player/Sounds/SoundSwordSwing.prefab.meta
  Assets/Prefabs/Player/Weapons/Bullet.prefab
  Assets/Prefabs/Player/Weapons/MeleeHitbox.prefab
  Assets/Prefabs/Player/Weapons/WeaponSword.prefab
  Assets/Scripts/Player/PlayerBullet.cs
  Assets/Scripts/Player/PlayerMelee.cs
  Assets/Scripts/Player/PlayerMeleeHitbox.cs
  Assets/Scripts/Player/PlayerMovement.cs
  Assets/Scripts/Player/PlayerShooting.cs
  UserSettings/EditorUserSettings.asset
Labels: enhancement, High Priority

#345 Add BGM
  Assets/3rd-Party/Audio/Soundtrack/Sunny Day - Reed Mathis.mp3.meta
  Assets/3rd-Party/Audio/Soundtrack/Wehrmut - Godmode.mp3
  Assets/3rd-Party/Audio/Soundtrack/Wehrmut - Godmode.mp3.meta
  Assets/3rd-Party/Audio/Soundtrack/When You're Not Looking - Nathan Moore.mp3.meta
  Assets/Prefabs/Audio.meta
  Assets/Prefabs/Audio/AudioManager.prefab
  Assets/Prefabs/Audio/AudioManager.prefab.meta
  Assets/Prefabs/AudioManager.prefab
  Assets/Prefabs/AudioManager.prefab.meta
  Assets/Scenes/Levels/ClownScene-beta.unity
  Assets/Scenes/Levels/GhostScene-beta.unity
  Assets/Scenes/Levels/SpiderScene-beta.unity
  Assets/Scenes/Levels/TutorialScene-beta.unity
  Assets/Scenes/Menu/Loadout.unity
  Assets/Scenes/Menu/Menu-beta.unity
  Assets/Scripts/GameManager/AudioManager.cs
  Assets/Scripts/UI/SettingsMenu.cs
  UserSettings/EditorUserSettings.asset
Labels: bug, enhancement

#346 Fix bgm game win loss
  Assets/Prefabs/Audio/AudioManager.prefab
  Assets/Prefabs/Enemy/Graveyards/Bullets/DemonBulletImpact.prefab
  Assets/Prefabs/Enemy/Spiders/Bullet/BulletImpactSpider.prefab
  Assets/Prefabs/Enemy/Tutorials/Bullets/BossBulletImpact.prefab
  Assets/Prefabs/Enemy/Tutorials/Bullets/BulletImpact.prefab
  Assets/Scenes/Levels/ClownScene-beta.unity
  Assets/Scenes/Levels/GhostScene-beta.unity
  Assets/Scenes/Levels/SpiderScene-beta.unity
  Assets/Scenes/Levels/TutorialScene-beta.unity
  Assets/Scripts/GameManager/AudioManager.cs
  Assets/Scripts/GameManager/GameStateManager.cs
  UserSettings/EditorUserSettings.asset
Labels: bug
